generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NjMenuItemRouting
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              MenuItemRouting
    plural:                MenuItemsRoutings
    route_prefix:          nj_menu_item_routing
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Menu Item Routing List
        display:  [=description, menu_order, NjSectionRouting, routing, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
