generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NjTrip
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              Trip
    plural:                Trips
    route_prefix:          nj_trip
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Trip List
        display:  [=description, njCalendar, njRoute, detail, created_at, updated_at]

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
