default:
  metas:
    title:        Administrative module for routes - NoJam
    
showSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false, common/maps/maps.core.js, backend/maps/maps]

editSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false, common/maps/maps.core.js, backend/maps/editable_maps, backend/njRoute]

newSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false, common/maps/maps.core.js, backend/maps/editable_maps, backend/njRoute]
