generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              Permission
    plural:                Permissions
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      form:
        display: [name, description, groups_list, users_list, menu_items_routings_list]