generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              User
    plural:                Users
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions